import {
  StethoscopeIcon,
  HeartIcon,
  Brain01Icon,
  Bone01Icon,
  ScissorIcon,
  Baby01Icon,
  EyeIcon,
  BandageIcon,
  Shield01Icon,
  KidneysIcon,
  BrainIcon,
  Hospital01Icon,
  Building01Icon,
  Building02Icon,
} from "@hugeicons/core-free-icons"
import type { ComponentType } from "react"
import type { HugeiconsProps } from "@hugeicons/react"

export type Icon = ComponentType<HugeiconsProps>

export const categories = [
  { name: "Medicine", icon: StethoscopeIcon, count: 45 },
  { name: "Cardiology", icon: HeartIcon, count: 18 },
  { name: "Neurology", icon: Brain01Icon, count: 12 },
  { name: "Orthopedics", icon: Bone01Icon, count: 15 },
  { name: "ENT", icon: StethoscopeIcon, count: 10 },
  { name: "Gynecology", icon: Baby01Icon, count: 20 },
  { name: "Child Specialist", icon: Baby01Icon, count: 22 },
  { name: "Eye Specialist", icon: EyeIcon, count: 9 },
  { name: "Skin Specialist", icon: BandageIcon, count: 14 },
  { name: "Psychiatry", icon: BrainIcon, count: 7 },
  { name: "Nephrology", icon: KidneysIcon, count: 6 },
  { name: "Urology", icon: Shield01Icon, count: 8 },
  { name: "Surgery", icon: ScissorIcon, count: 16 },
]

export const doctors = [
  {
    id: 1,
    name: "Dr. Ayesha Rahman",
    specialty: "Cardiology",
    qualifications: "MBBS, MD (Cardiology)",
    hospital: "Khulna Medical College",
    district: "Khulna",
    gender: "Female",
    experience: 15,
    rating: 4.9,
    reviews: 312,
    available: true,
    availability: "Available Today",
    consultationType: "Both",
    languages: ["Bangla", "English"],
    fee: 1500,
  },
  {
    id: 2,
    name: "Dr. Mohammad Hasan",
    specialty: "Neurology",
    qualifications: "MBBS, FCPS (Neurology)",
    hospital: "Star Hospital & Diagnostic",
    district: "Khulna",
    gender: "Male",
    experience: 12,
    rating: 4.8,
    reviews: 245,
    available: true,
    availability: "Available This Week",
    consultationType: "In-Person",
    languages: ["Bangla", "English"],
    fee: 2000,
  },
  {
    id: 3,
    name: "Dr. Fatema Begum",
    specialty: "Gynecology",
    qualifications: "MBBS, DGO, FCPS (OB/GYN)",
    hospital: "Bagerhat District Hospital",
    district: "Bagerhat",
    gender: "Female",
    experience: 10,
    rating: 4.9,
    reviews: 428,
    available: false,
    availability: "Unavailable",
    consultationType: "In-Person",
    languages: ["Bangla"],
    fee: 1200,
  },
  {
    id: 4,
    name: "Dr. Kabirul Islam",
    specialty: "Orthopedics",
    qualifications: "MBBS, MS (Orthopedics)",
    hospital: "Khulna Medical College",
    district: "Khulna",
    gender: "Male",
    experience: 18,
    rating: 4.7,
    reviews: 189,
    available: true,
    availability: "Available Today",
    consultationType: "Both",
    languages: ["Bangla", "English"],
    fee: 1800,
  },
  {
    id: 5,
    name: "Dr. Nusrat Jahan",
    specialty: "Skin Specialist",
    qualifications: "MBBS, DDV (Dermatology)",
    hospital: "Star Hospital & Diagnostic",
    district: "Khulna",
    gender: "Female",
    experience: 8,
    rating: 4.8,
    reviews: 156,
    available: true,
    availability: "Available This Week",
    consultationType: "Video Call",
    languages: ["Bangla", "English"],
    fee: 1000,
  },
  {
    id: 6,
    name: "Dr. Anisur Rahman",
    specialty: "Medicine",
    qualifications: "MBBS, MD (Internal Medicine)",
    hospital: "Bagerhat District Hospital",
    district: "Bagerhat",
    gender: "Male",
    experience: 20,
    rating: 4.6,
    reviews: 534,
    available: true,
    availability: "Available Today",
    consultationType: "In-Person",
    languages: ["Bangla"],
    fee: 800,
  },
  {
    id: 7,
    name: "Dr. Sabrina Akter",
    specialty: "Child Specialist",
    qualifications: "MBBS, DCH, FCPS (Pediatrics)",
    hospital: "Khulna Medical College",
    district: "Khulna",
    gender: "Female",
    experience: 11,
    rating: 4.9,
    reviews: 367,
    available: false,
    availability: "Unavailable",
    consultationType: "Both",
    languages: ["Bangla", "English"],
    fee: 1000,
  },
  {
    id: 8,
    name: "Dr. Rafiqul Islam",
    specialty: "ENT",
    qualifications: "MBBS, MS (ENT)",
    hospital: "Star Hospital & Diagnostic",
    district: "Khulna",
    gender: "Male",
    experience: 14,
    rating: 4.7,
    reviews: 201,
    available: true,
    availability: "Available This Week",
    consultationType: "In-Person",
    languages: ["Bangla", "English"],
    fee: 1200,
  },
  {
    id: 9,
    name: "Dr. Kamrun Nahar",
    specialty: "Eye Specialist",
    qualifications: "MBBS, FCPS (Ophthalmology)",
    hospital: "Khulna Medical College",
    district: "Khulna",
    gender: "Female",
    experience: 9,
    rating: 4.8,
    reviews: 178,
    available: true,
    availability: "Available Today",
    consultationType: "Both",
    languages: ["Bangla", "English"],
    fee: 1000,
  },
  {
    id: 10,
    name: "Dr. Hashem Ali",
    specialty: "Surgery",
    qualifications: "MBBS, MS (General Surgery)",
    hospital: "Bagerhat District Hospital",
    district: "Bagerhat",
    gender: "Male",
    experience: 16,
    rating: 4.7,
    reviews: 290,
    available: true,
    availability: "Available This Week",
    consultationType: "In-Person",
    languages: ["Bangla"],
    fee: 2000,
  },
  {
    id: 11,
    name: "Dr. Sharmin Sultana",
    specialty: "Psychiatry",
    qualifications: "MBBS, FCPS (Psychiatry)",
    hospital: "Star Hospital & Diagnostic",
    district: "Khulna",
    gender: "Female",
    experience: 7,
    rating: 4.9,
    reviews: 142,
    available: true,
    availability: "Available Today",
    consultationType: "Video Call",
    languages: ["Bangla", "English"],
    fee: 1500,
  },
  {
    id: 12,
    name: "Dr. Zahangir Alam",
    specialty: "Nephrology",
    qualifications: "MBBS, MD (Nephrology)",
    hospital: "Khulna Medical College",
    district: "Khulna",
    gender: "Male",
    experience: 13,
    rating: 4.6,
    reviews: 165,
    available: false,
    availability: "Unavailable",
    consultationType: "Both",
    languages: ["Bangla", "English"],
    fee: 1800,
  },
]

export const hospitals = [
  {
    id: 1,
    name: "Khulna Medical College",
    address: "Sher-e-Bangla Road, Khulna",
    phone: "+880 41-XXXXXXX",
    icon: Hospital01Icon,
  },
  {
    id: 2,
    name: "Bagerhat District Hospital",
    address: "Bagerhat Sadar, Bagerhat",
    phone: "+880 46-XXXXXXX",
    icon: Building01Icon,
  },
  {
    id: 3,
    name: "Star Hospital & Diagnostic",
    address: "Sonadanga, Khulna",
    phone: "+880 41-XXXXXXX",
    icon: Building02Icon,
  },
]

export const articles = [
  {
    id: 1,
    title: "Understanding Heart Disease: Prevention and Early Detection",
    category: "Cardiology",
    readTime: "5 min",
    excerpt:
      "Learn about the risk factors, symptoms, and preventive measures for heart disease.",
  },
  {
    id: 2,
    title: "Child Vaccination Schedule: A Complete Guide for Parents",
    category: "Pediatrics",
    readTime: "4 min",
    excerpt:
      "Everything you need to know about your child's vaccination timeline.",
  },
  {
    id: 3,
    title: "Mental Health in Modern Life: Strategies for Wellbeing",
    category: "Mental Health",
    readTime: "6 min",
    excerpt:
      "Practical tips for maintaining mental wellness in today's fast-paced world.",
  },
]

export const specialtyNames = categories.map((c) => c.name)
export const hospitalNames = hospitals.map((h) => h.name)
export const districts = ["Khulna", "Bagerhat"]
export const genders = ["Male", "Female"]
export const consultationTypes = ["In-Person", "Video Call", "Both"]
export const availabilityOptions = [
  "Available Today",
  "Available This Week",
  "Unavailable",
]

export const experienceRanges = [
  { label: "0–5 years", min: 0, max: 5 },
  { label: "5–10 years", min: 5, max: 10 },
  { label: "10–15 years", min: 10, max: 15 },
  { label: "15+ years", min: 15, max: Infinity },
]

export const feeRanges = [
  { label: "Under ৳1,000", min: 0, max: 999 },
  { label: "৳1,000 – ৳1,500", min: 1000, max: 1500 },
  { label: "৳1,500 – ৳2,000", min: 1500, max: 2000 },
  { label: "৳2,000+", min: 2000, max: Infinity },
]

export const sortOptions = [
  "Newest",
  "Most Experienced",
  "Highest Rated",
  "Lowest Fee",
  "Highest Fee",
  "Alphabetical",
] as const
