export const medicalSpecialties = [
  { value: "cardiology", label: "Cardiology" },
  { value: "dermatology", label: "Dermatology" },
  { value: "endocrinology", label: "Endocrinology" },
  { value: "ENT", label: "ENT (Ear, Nose & Throat)" },
  { value: "gastroenterology", label: "Gastroenterology" },
  { value: "general_surgery", label: "General Surgery" },
  { value: "geriatrics", label: "Geriatrics" },
  { value: "gynecology", label: "Gynecology & Obstetrics" },
  { value: "hematology", label: "Hematology" },
  { value: "hepatology", label: "Hepatology" },
  { value: "infectious_disease", label: "Infectious Diseases" },
  { value: "internal_medicine", label: "Internal Medicine" },
  { value: "nephrology", label: "Nephrology" },
  { value: "neurology", label: "Neurology" },
  { value: "neurosurgery", label: "Neurosurgery" },
  { value: "oncology", label: "Oncology" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "orthopedics", label: "Orthopedics" },
  { value: "otolaryngology", label: "Otolaryngology" },
  { value: "pathology", label: "Pathology" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "physical_medicine", label: "Physical Medicine & Rehabilitation" },
  { value: "plastic_surgery", label: "Plastic & Reconstructive Surgery" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "pulmonology", label: "Pulmonology" },
  { value: "radiology", label: "Radiology & Imaging" },
  { value: "renal", label: "Renal Medicine" },
  { value: "rheumatology", label: "Rheumatology" },
  { value: "sports_medicine", label: "Sports Medicine" },
  { value: "thoracic_surgery", label: "Thoracic Surgery" },
  { value: "urology", label: "Urology" },
  { value: "dental", label: "Dental & Oral Surgery" },
  { value: "breast_surgery", label: "Breast Surgery" },
  { value: "cardiac_surgery", label: "Cardiac Surgery" },
  { value: "colorectal_surgery", label: "Colorectal Surgery" },
  { value: "endocrine_surgery", label: "Endocrine Surgery" },
  { value: "hepatobiliary_surgery", label: "Hepatobiliary Surgery" },
  { value: "pediatric_surgery", label: "Pediatric Surgery" },
  { value: "transplant_surgery", label: "Transplant Surgery" },
  { value: "vascular_surgery", label: "Vascular Surgery" },
  { value: "anesthesiology", label: "Anesthesiology" },
  { value: "emergency_medicine", label: "Emergency Medicine" },
  { value: "family_medicine", label: "Family Medicine" },
  { value: "general_practice", label: "General Practice" },
  { value: "immunology", label: "Immunology" },
  { value: "neonatology", label: "Neonatology" },
  { value: "obstetrics", label: "Obstetrics" },
  { value: "pain_medicine", label: "Pain Medicine" },
  { value: "palliative_care", label: "Palliative Care" },
  { value: "sleep_medicine", label: "Sleep Medicine" },
] as const
